['.etc/hosts']
type = 'file'
url = 'https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts'
refreshPeriod = '24h'

['.config/alacritty/colors.yml']
type = 'file'
url = 'https://raw.githubusercontent.com/nordtheme/alacritty/main/src/nord.yaml'
refreshPeriod = '168h'
filter.command = 'sed'
filter.args = ['s/^    bar:$/  footer_bar:/']

['.config/dircolors']
type = 'file'
url = 'https://raw.githubusercontent.com/nordtheme/dircolors/develop/src/dir_colors'
refreshPeriod = '168h'

['.config/kitty_keys/kitty_keys.sh']
type = 'file'
url = 'https://raw.githubusercontent.com/flexibeast/kitty_keys/main/kitty_keys.sh'
refreshPeriod = '168h'

['.config/nano/syntax_highlighting']
type = 'archive'
url = 'https://github.com/scopatz/nanorc/archive/master.tar.gz'
exact = true
stripComponents = 1
refreshPeriod = '168h'
include = ['*/*.nanorc']

['.config/nvim/colors/nord.vim']
type = 'file'
url = 'https://raw.githubusercontent.com/nordtheme/vim/main/colors/nord.vim'
refreshPeriod = '168h'

['.config/tilix/schemes/nord.json']
type = 'file'
url = 'https://raw.githubusercontent.com/arcticicestudio/nord-tilix/develop/src/json/nord.json'
refreshPeriod = '168h'

['.config/Xresources']
type = 'file'
url = 'https://raw.githubusercontent.com/arcticicestudio/nord-xresources/develop/src/nord'
refreshPeriod = '168h'

['.local/share/gedit/styles/nord.xml']
type = 'file'
url = 'https://raw.githubusercontent.com/arcticicestudio/nord-gedit/develop/src/xml/nord.xml'
refreshPeriod = '168h'

['.local/share/konsole/nord.colorscheme']
type = 'file'
url = 'https://raw.githubusercontent.com/arcticicestudio/nord-konsole/develop/src/nord.colorscheme'
refreshPeriod = '168h'

['.local/share/xfce4/terminal/colorschemes/nord.theme']
type = 'file'
url = 'https://raw.githubusercontent.com/arcticicestudio/nord-xfce-terminal/develop/src/nord.theme'
refreshPeriod = '168h'

['Code/scripts']
type = 'git-repo'
url = 'git@github.com:rvenutolo/scripts.git'
